# Generated by Django 5.0 on 2025-03-14 07:40

import django.db.models.deletion
import weixin_miniprogram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activities', models.JSONField(default=list)),
                ('created_at', models.BigIntegerField(default=weixin_miniprogram.models.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=weixin_miniprogram.models.current_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('order_num', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='weixin_miniprogram.checklist')),
            ],
        ),
    ]
