# Generated by Django 5.2 on 2025-10-16 09:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_weixin_id', models.CharField(max_length=255, verbose_name='用户微信ID')),
                ('creator_weixin_name', models.CharField(max_length=255, verbose_name='用户微信名称')),
                ('activity_title', models.CharField(max_length=255, verbose_name='活动名称')),
                ('activity_item', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='活动事项列表')),
                ('white_list', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='白名单')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
            },
        ),
    ]
