# Generated by Django 5.0 on 2025-02-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='UserActivity',
        ),
    ]
