# Generated by Django 5.0 on 2025-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0002_rename_activity_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
