# Generated by Django 5.2 on 2025-10-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0002_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
