# Generated by Django 5.2 on 2025-10-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0003_delete_useractivity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Activities',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='activity_item',
            new_name='activity_items',
        ),
    ]
