# Generated by Django 5.2 on 2025-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0004_rename_activity_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': '微信用户信息',
                'verbose_name_plural': '微信用户信息',
                'db_table': 'weixin_user_info',
            },
        ),
    ]
