# Generated by Django 5.0 on 2025-03-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unique_key',
        ),
    ]
