# Generated by Django 5.2 on 2025-11-06 09:45

import weixin_miniprogram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0005_weixinuserinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weixinuserinfo',
            options={},
        ),
        migrations.AddField(
            model_name='weixinuserinfo',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=weixin_miniprogram.models.user_avatar_path, verbose_name='头像文件'),
        ),
    ]
