# Generated by Django 5.0 on 2025-03-04 09:25

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0005_remove_item_unique_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='weixin_miniprogram.checklist', verbose_name='父清单')),
            ],
            options={
                'verbose_name': '清单',
                'verbose_name_plural': '清单列表',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
