# Generated by Django 5.0 on 2025-03-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0006_checklist_delete_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={},
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='level',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='weixin_miniprogram.checklist'),
        ),
    ]
