# Generated by Django 5.2 on 2025-11-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0006_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weixinuserinfo',
            name='avatar_url',
        ),
    ]
