# Generated by Django 5.2 on 2025-11-07 03:05

import django.core.serializers.json
import weixin_miniprogram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0007_remove_weixinuserinfo_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weixinuserinfo',
            old_name='openid',
            new_name='weixin_id',
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_items',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activities',
            name='creator_weixin_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activities',
            name='creator_weixin_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activities',
            name='white_list',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='weixinuserinfo',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=weixin_miniprogram.models.user_avatar_path),
        ),
    ]
