# Generated by Django 5.2 on 2025-11-12 06:44

import weixin_miniprogram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0008_rename_openid_weixinuserinfo_weixin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='created_at',
            field=models.IntegerField(default=weixin_miniprogram.models.current_timestamp),
        ),
        migrations.AddField(
            model_name='activities',
            name='updated_at',
            field=models.IntegerField(default=weixin_miniprogram.models.current_timestamp),
        ),
    ]
