# Generated by Django 5.2 on 2025-11-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0009_activities_created_at_activities_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='created_at',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='updated_at',
        ),
    ]
