# Generated by Django 5.2 on 2025-11-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_miniprogram', '0010_rename_created_at_activities_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
