# Generated by Django 5.0 on 2025-01-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(db_index=True)),
                ('source_code', models.TextField()),
                ('knowledge', models.TextField()),
            ],
        ),
    ]
