# Generated by Django 5.0 on 2025-01-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_naive_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
