# Generated by Django 5.0 on 2025-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_naive_book', '0003_rename_lessons_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='knowledge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='source_code',
            field=models.TextField(blank=True),
        ),
    ]
