# Generated by Django 6.0.3 on 2026-03-10 02:55

import django.core.serializers.json
import weixin_miniprogram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_weixin_id', models.CharField(max_length=255)),
                ('creator_weixin_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(default='', max_length=255)),
                ('activity_title', models.CharField(max_length=255)),
                ('activity_items', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('white_list', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('last_modified', models.IntegerField(default=weixin_miniprogram.models.current_timestamp)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='WeixinUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weixin_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to=weixin_miniprogram.models.user_avatar_path)),
            ],
            options={
                'db_table': 'weixin_user_info',
            },
        ),
    ]
