"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 默认值与原提交保持一致，线上通过环境变量 DJANGO_SECRET_KEY 覆盖。
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-9m%v^676#51-!9icf8d5u-)ox7!t$@e)m^*4n%nlf4af*$1+&&',
)


def _env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default):
    raw = os.getenv(name, '')
    if not raw.strip():
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', False)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS',
                          ['www.lian-yolo.com', 'lian-yolo.com'])
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS',
                                 ['https://www.lian-yolo.com', 'https://lian-yolo.com'])

# 微信小程序的 AppID / AppSecret，请在服务器环境变量中设置，不要写进代码。
WEIXIN_MINIPROGRAM_APP_ID = os.getenv('WEIXIN_MINIPROGRAM_APP_ID', '')
WEIXIN_MINIPROGRAM_APP_SECRET = os.getenv('WEIXIN_MINIPROGRAM_APP_SECRET', '')

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")   # collected by collectstatic

# ---------------------------------------------------------------------------
# 媒体文件（用户头像）
# ---------------------------------------------------------------------------
# 头像的存储路径由 models.user_avatar_path 决定，返回的是相对路径
# 'avatars/weixin/<openid>/<随机名>.<ext>'。
# 线上 nginx 用 `location /avatars/ { alias /root/lian-yolo.com/backend/avatars/; }`
# 对外提供，而 gunicorn 的工作目录正好是 backend/，因此历史数据落盘在
# backend/avatars/weixin/... ，对外 URL 形如 /avatars/weixin/... 。
# 这里把这两个隐式约定显式写出来：MEDIA_ROOT 指向 backend/，MEDIA_URL 用根路径，
# 落盘位置与对外 URL 与线上完全一致（不会产生 avatars/avatars 这种叠加）。
MEDIA_ROOT = BASE_DIR
MEDIA_URL = '/'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'weixin_miniprogram',
]

# 小程序只消费 JSON，关掉 DRF 的 HTML 渲染（Browsable API 不再暴露）。
# 这样 /weixin-miniprogram/api/ 下的响应格式是确定的 JSON，不会因为
# 请求头不同而变成 HTML 页面。
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


LOG_DIR = BASE_DIR / 'logs'
if not LOG_DIR.exists():
    LOG_DIR.mkdir()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['file', 'console'],
    },
}
