# Generated by Django 5.0 on 2024-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadpdf',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='file_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
