# Generated by Django 5.0 on 2024-12-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockbasicinfo_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockbasicinfo',
            constraint=models.UniqueConstraint(fields=('date', 'code'), name='unique_date_code'),
        ),
    ]
