# Generated by Django 5.0 on 2025-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockbasicinfo_unique_date_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('level', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('sw_l2', models.CharField(db_index=True, max_length=10)),
                ('sw_l3', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
