# Generated by Django 5.0 on 2025-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_industris_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industris',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockbasicinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
