# Generated by Django 5.0 on 2025-01-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_stockbasicinfo_stocktradeinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Industris',
            new_name='Industry',
        ),
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
