# Generated by Django 5.0 on 2025-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_rename_industris_industry_rename_stocks_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('industry', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
