# Generated by Django 5.0 on 2025-02-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_industrystock_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
