# Generated by Django 5.0 on 2024-11-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='DoubanPost',
        ),
    ]
