# Generated by Django 5.0 on 2024-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0002_rename_post_doubanpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanpost',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
