# Generated by Django 5.0 on 2024-12-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0003_doubanpost_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanpost',
            name='good',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='doubanpost',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='doubanpost',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
