name: Deploy to Aliyun
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source /root/django-5.0/bin/activate
            cd /root/lian-yolo.com/mysite
            git pull origin main
            python3 manage.py collectstatic --noinput
            python3 manage.py migrate

            supervisorctl restart lian-yolo
